export const LOADING_PRODUCT = "[PRODUCT] LOADING_PRODUCT";
export const LOADING_PRODUCT_FULFILLED = "[PRODUCT] LOADING_PRODUCT_FULFILLED";
export const LOADING_PRODUCT_FAILED = "[PRODUCT] LOADING_PRODUCT_FAILED";

export const TOGGLE_PRODUCT_DETAIL = "[PRODUCT_DETAIL] TOGGLE_PRODUCT_DETAIL";